shopware_app_routes_lifecycle:
  resource: '@ShopwareAppBundle/Resources/config/routing/lifecycle.xml'

shopware_app_routes_webhook:
  resource: '@ShopwareAppBundle/Resources/config/routing/webhook.xml'